import "./globals.css";

import type { Metadata } from "next";

import { cn } from "@/lib/utils";

import WrapConnectKitProvider from "@/providers/WrapConnectKitProvider";
import UIProvider from "@/providers/UIProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("bg-background")}>
        <UIProvider>
          <WrapConnectKitProvider>{children}</WrapConnectKitProvider>
        </UIProvider>
      </body>
    </html>
  );
}
