import "./globals.css";

import type { Metadata } from "next";

import { cn } from "@/lib/utils";

import WrapConnectKitProvider from "@/providers/WrapConnectKitProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("bg-background")}>
        <WrapConnectKitProvider>{children}</WrapConnectKitProvider>
      </body>
    </html>
  );
}
